using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NetParse
{
    public enum CharacterID : byte
    {
        JOHN_HATHORNE,
        GILES_COREY,
        MARY_WARREN,
        ABIGAIL_WILLIAMS,
        JOHN_PROCTOR,
        BETTY_PARRIS,
        ENTOAN_THE_PACK,
        MEG_TURNEY,
        THE_RPG_MINX,
        LORD_MINION_777,
        WARRIOR_YETI,
        DARK_REVENANT,
        DLIVE,
        OHM_WRECKER,
        KRISTIAN,
        JESTER,
        WITCH,
        SHERIFF,
        DOCTOR,
        DEXTER,
        SLEUTH,
        FIREBUG,
        THE_TESH_TUBE,
        MONTGOMERY_MONEYBAGS,
        FIRE_IT_UP,
        HEADLESS_HORSEMAN,
        LYCANTHROPE,
        JOHN_VOXEL,
        SANTA_CLAUS,
        NURSE_LILLIAN,
        GUARDIAN,
        NURSE_JOY,
        CANDY,
        MS_DIRECTION,
        GRIM_REAPER,
        PIRATE,
        WARDEN,
        DRACULA,
        VAMPIRE_HUNTER,
        COGNITION,
        ROBOT_SANTA,
        THE_GODFATHER,
        RED_RIDING_HOOD,
        MILLICENT_MONEYBAGS,
        URIEL,
        CRIMSON_REAPER,
        AMNESIAC,
        YUAN_ITOR,
        TAMER_OF_FROST,
        TAMER_OF_FLAMES,
        TAMER_OF_THUNDER,
        BARTHULE_OF_FAR_RIVER,
        THE_CRIMSON_KATANA,
        BROCK_SMITH,
        BEELZEBUB,
        NOSFERATU,
        PRINCE,
        PRINCESS,
        KNIGHT,
        ARCHER,
        QUEEN,
        KING,
        KRAMPUS,
        RAMBO_SANTA,
        STEAM_BOT_3000,
        NECROMANCER,
        POTION_MASTER,
        CRUSADER,
        POISONER,
        MEDUSA,
        PLAGUEBEARER,
        JACK_FROST,
        JUDGE,
        ALABASTER_REAPER,
        MONTY_MONEYBAGS
    }
}
