using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NetParse
{
    public enum RoleID : byte
    {
        BODYGUARD,
        DOCTOR,
        ESCORT,
        INVESTIGATOR,
        JAILOR,
        LOOKOUT,
        MAYOR,
        MEDIUM,
        RETRIBUTIONIST,
        SHERIFF,
        SPY,
        TRANSPORTER,
        VAMPIRE_HUNTER,
        VETERAN,
        VIGILANTE,
        BLACKMAILER,
        CONSIGLIERE,
        CONSORT,
        DISGUISER,
        FORGER,
        FRAMER,
        GODFATHER,
        JANITOR,
        MAFIOSO,
        AMNESIAC,
        ARSONIST,
        EXECUTIONER,
        JESTER,
        SERIAL_KILLER,
        SURVIVOR,
        VAMPIRE,
        WEREWOLF,
        WITCH,
        RANDOM_TOWN,
        TOWN_INVESTIGATIVE,
        TOWN_PROTECTIVE,
        TOWN_KILLING,
        TOWN_SUPPORT,
        RANDOM_MAFIA,
        MAFIA_SUPPORT,
        MAFIA_DECEPTION,
        RANDOM_NEUTRAL,
        NEUTRAL_BENIGN,
        NEUTRAL_EVIL,
        NEUTRAL_KILLING,
        ANY,
        CRUSADER,
        TRACKER,
        TRAPPER,
        PSYCHIC,
        HYPNOTIST,
        AMBUSHER,
        PLAGUEBEARER,
        JUGGERNAUT,
        GUARDIAN_ANGEL,
        PIRATE,
        COVEN_LEADER,
        POTION_MASTER,
        HEX_MASTER,
        NECROMANCER,
        POISONER,
        MEDUSA,
        COVEN_RANDOM_COVEN,
        COVEN_RANDOM_TOWN,
        COVEN_TOWN_INVESTIGATIVE,
        COVEN_TOWN_PROTECTIVE,
        COVEN_TOWN_KILLING,
        COVEN_TOWN_SUPPORT,
        COVEN_RANDOM_MAFIA,
        COVEN_MAFIA_SUPPORT,
        COVEN_MAFIA_DECEPTION,
        COVEN_RANDOM_NEUTRAL,
        COVEN_NEUTRAL_BENIGN,
        COVEN_NEUTRAL_CHAOS,
        COVEN_NEUTRAL_EVIL,
        COVEN_NEUTRAL_KILLING,
        COVEN_ANY,
        PESTILENCE = 101,
        GHOUL = 102,
        CLEANED = 201,
        STONED = 202
    }
}
